services:
  database:
    build:
      context: .
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pgstac
      - PGUSER=username
      - PGPASSWORD=password
      - PGDATABASE=pgstac
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d pgstac"]
      interval: 1s
      timeout: 1s
      retries: 20
  migrate:
    build:
      context: .
    environment:
      - SQITCH_TARGET=db:pg://username:password@database:5432/pgstac
    depends_on:
      database:
        condition: service_healthy
    command: sqitch deploy
